export const productList3 = (
    [
        {
            'key':1,
            'id':1,
            'name':'笔记本1',
            'img':[],
            'num':1,
            'stock':100,
            'unit':"1本",
        },
        {
            'key':2,
            'id':2,
            'name':'笔记本2',
            'img':[],
            'num':1,
            'stock':100,
            'unit':"1本",
        },
        {
            'key':3,
            'id':3,
            'name':'笔记本3',
            'img':[],
            'num':1,
            'stock':100,
            'unit':"1本",
        },
        {
            'key':4,
            'id':4,
            'name':'笔记本4',
            'img':[],
            'num':1,
            'stock':100,
            'unit':"1本",
        },
        {
            'key':5,
            'id':5,
            'name':'笔记本5',
            'img':[],
            'num':1,
            'stock':100,
            'unit':"1本",
        },
    ]
)